### ISSUE TITLE
Creating APIs to deploy in AWS.

### ISSUE THREAD

**Issue by AshfakAhmedd** [williamboomer87/project-publish-ai#19]
- [x] Generate Cover Image
- [x] Initial Form
- [x] Grammar check using DeepGram
- [x] Grammar check using RapidAPI
- [x] Upload audio file

**Comment by abhiru-wije** [comment]
Tested and Successfully Deployed to AWS EC2 (w/o upload)

**Comment by abhiru-wije** [comment]
Upload API also developed and deployed successfully into AWS EC2 instance
